packages:
  - "apps/*"
  - "packages/*"
  - "docs/site"
  - "docs/slides"
catalogs:
  prod:
    "@tauri-apps/api": ^2.10.1
    "@tauri-apps/plugin-autostart": ^2.4.1
    "@tauri-apps/plugin-dialog": ^2.4.0
    "@tauri-apps/plugin-store": ^2.4.0
  frontend:
    vue: ^3.5.13
    pinia: ^3.0.4
    "@vueuse/core": ^14.2.1
    unocss: ^66.6.0
    vue-router: ^4.5.1
    lucide-vue-next: ^0.575.0
    vite: ^6.4.1
    "@vitejs/plugin-vue": ^5.2.1
    vitest: ^3.2.4
    "@vitest/coverage-v8": 3.2.4
    "@vue/test-utils": ^2.4.6
    vitepress: ^1.6.4
    "@slidev/cli": ^52.12.0
    "@slidev/theme-default": ^0.25.0
    tsdown: ^0.20.3
  dev:
    "@types/web-bluetooth": ^0.0.21
    typescript: ^5.9.3
    jsdom: ^26.1.0
    "@playwright/test": ^1.50.0
  inlined:
    turbo: ^2.8.10
    "@tauri-apps/cli": ^2.10.0
